# Generated by Django 6.0.5 on 2026-05-07 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('popis', models.TextField()),
                ('postup', models.TextField()),
                ('doba_pripravy', models.IntegerField(help_text='Čas v minutách')),
                ('pocet_porcí', models.IntegerField()),
                ('fotka', models.ImageField(blank=True, null=True, upload_to='recepty/')),
                ('datum_pridani', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kategorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recepty.kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('mnozstvi', models.CharField(max_length=50)),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredience', to='recepty.recept')),
            ],
        ),
        migrations.CreateModel(
            name='Hodnoceni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hvezdicky', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('komentar', models.TextField(blank=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hodnoceni', to='recepty.recept')),
            ],
        ),
    ]
