# Generated by Django 6.0.5 on 2026-05-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recept',
            name='pocet_porcí',
        ),
        migrations.AddField(
            model_name='recept',
            name='pocet_porci',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ingredience',
        ),
    ]
