# Generated by Django 6.0.5 on 2026-05-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0002_remove_recept_pocet_porcí_recept_pocet_porci_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hodnoceni',
        ),
    ]
